litellm:
  # base_url: "http://host.docker.internal:18080"
  base_url: "http://host.docker.internal:4000/bedrock"
  timeout: 30000

proxy:
  forward_headers: true
  forward_response_headers: true

server:
  port: 3000
  host: "0.0.0.0"
